### ISSUE TITLE
-nicole & brandon

### ISSUE THREAD

**Issue by nicolecheng** [MKotlik/login-MishaK#1]
idk man
$ python app.py 
  File "app.py", line 109
    session['username'] = username #log user into session
    ^
IndentationError: expected an indented block

it looks nice and there are lots of comments
why are there semicolons?
v fancy shmancy jinja stuff

you should fix it, bc it seems like it would be a bomb website!!!!

**Comment by MKotlik** [comment]
Program was not running because sessions was in-process of being added. Sessions added, issue resolved.

Thanks for the compliments!!! :smile:
